apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-portfolio-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: static-portfolio-website
          image: ujjwalmahar/static-portfolio-website
          ports:
            - containerPort: 80
