# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: static-portfolio-website
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: web-app
#   template:
#     metadata:
#       labels:
#         app: web-app
#     spec:
#       containers:
#         - name: static-portfolio-website
#           image: sivasaileo/html-webpage
#           ports:
#             - containerPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-portfolio-website
  namespace: sivasai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-portfolio-website
  template:
    metadata:
      labels:
        app: static-portfolio-website
    spec:
      containers:
      - name: static-portfolio-website
        image: sivasaileo/static-portfolio-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
